version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    env_file: .env
    container_name: mariadb
    restart: always
    ports:
      - '3306:3306'
    networks:
      - inception
    volumes:
      - db-data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    image: wordpress
    container_name: wordpress
    restart: always
    expose:
      - '9000'
    env_file: .env
    networks:
      - inception
    volumes:
      - web-data:/var/www/html

  nginx:
    build: ./requirements/nginx
    depends_on:
      wordpress:
        condition: service_healthy
        restart: true
    image: nginx:inception
    container_name: nginx
    restart: always
    ports:
      - '443:443'
    env_file:
      - .env
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/wonie/Downloads/zammanboInception/srcs/data
  web-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/wonie/Downloads/zammanboInception/srcs/web
